;;; Dispatcher C source emission.
;;;
;;; Generates dispatch.c, the single translation unit that exposes
;;; the public C ABI to consumers and stitches the per-chunk
;;; functions together. The dispatcher provides
;;;
;;;   int    get_n(void);
;;;   int    get_k(void);
;;;   void   compute_residual(const double *state, double *out_r);
;;;   void   compute_update  (const double *state_curr, double *state_next);
;;;
;;; plus forward declarations for every chunk function and any
;;; inline helper a chunk references that is not provided by libm.
;;; The only non-libm helper the standard vocabulary registers is
;;; cp_reciprocal, used by the solver when isolating a target whose
;;; coefficient is state-dependent. The dispatcher emits its
;;; definition inline so the build does not need to link an extra
;;; object.
;;;
;;; Pure-functional: returns a single C source string. The
;;; persistence layer writes it to disk.

(in-package #:compose-physics)


(defun emit-dispatch-c (problem
                        &key residual-chunks update-chunks)
  "Emit the dispatch.c source string for PROBLEM, given lists of
   chunk-source records produced by emit-residual-chunks and
   emit-update-chunks. The result is a complete translation unit
   ready to be compiled alongside the chunk sources."
  (check-type problem problem)
  (let* ((slot-count (problem-slot-count problem))
         (residual-count (problem-residual-count problem)))
    (with-output-to-string (stream)

      (format stream "/* dispatch.c — generated by compose-physics. */~%")
      (format stream "/* Problem: ~A */~%~%" (problem-name problem))

      (format stream "/* Forward declarations for chunk functions. */~%")
      (dolist (chunk residual-chunks)
        (format stream
                "extern void ~A(const double *state, double *out_r);~%"
                (chunk-source-function-name chunk)))
      (dolist (chunk update-chunks)
        (format stream
                "extern void ~A(const double *state_curr, double *state_next);~%"
                (chunk-source-function-name chunk)))
      (terpri stream)

      (format stream "int get_n(void) { return ~D; }~%" slot-count)
      (format stream "int get_k(void) { return ~D; }~%~%" residual-count)

      (format stream "void compute_residual(const double *state, double *out_r) {~%")
      (dolist (chunk residual-chunks)
        (format stream "    ~A(state, out_r);~%"
                (chunk-source-function-name chunk)))
      (format stream "}~%~%")

      (format stream
              "void compute_update(const double *state_curr, double *state_next) {~%")
      (dolist (chunk update-chunks)
        (format stream "    ~A(state_curr, state_next);~%"
                (chunk-source-function-name chunk)))
      (format stream "}~%"))))


;;; Inline self-checks. Build a small problem, generate chunks, then
;;; emit the dispatcher and verify it has the expected surface and
;;; references.

(eval-when (:load-toplevel :execute)

  ;; Problem with one residual that uses :sin (math.h-resolved) and
  ;; one update with no apply nodes. No reciprocal helper needed.
  (let* ((problem (make-problem
                   :name "dispatch-self-check"
                   :slot-names '("a" "b")
                   :residual-specs
                   (list (cons "row-1"
                               (sum (apply :sin (term 1.0d0 0 :name "a"))
                                    (scale -1.0d0 (term 1.0d0 1 :name "b")))))))
         (residual-chunks (emit-residual-chunks problem :chunk-row-count 8))
         (update-chunks   (emit-update-chunks   problem :chunk-row-count 8))
         (source (emit-dispatch-c problem
                                  :residual-chunks residual-chunks
                                  :update-chunks update-chunks)))
    (assert (search "get_n(void) { return 2; }" source))
    (assert (search "get_k(void) { return 1; }" source))
    (assert (search "compute_residual(const double *state, double *out_r)"
                    source))
    (assert (search "compute_update(const double *state_curr, double *state_next)"
                    source))
    (assert (search "compute_residual_chunk_000" source))
    (assert (search "compute_update_chunk_000" source))
    (assert (not (search "cp_reciprocal" source)) ()
            "dispatch.c never emits cp_reciprocal; chunk files do"))

  ;; Problem whose update form uses reciprocal. Build a relation
  ;; m*v_next - m*v - F*dt = 0 and solve for v_next; that produces a
  ;; tree containing apply :reciprocal which the dispatcher must
  ;; provide inline.
  (let* ((problem (make-problem
                   :name "dispatch-reciprocal-self-check"
                   :slot-names '("v_next" "v" "F" "dt" "m")
                   :residual-specs
                   (list (cons "newton-impulse"
                               (sum (product (term 1.0d0 4 :name "m")
                                             (term 1.0d0 0 :name "v_next"))
                                    (scale -1.0d0
                                           (product (term 1.0d0 4 :name "m")
                                                    (term 1.0d0 1 :name "v")))
                                    (scale -1.0d0
                                           (product (term 1.0d0 2 :name "F")
                                                    (term 1.0d0 3 :name "dt"))))))
                   :update-specs
                   (list
                    (cons "v_next"
                          (solve-for
                           (sum (product (term 1.0d0 4 :name "m")
                                         (term 1.0d0 0 :name "v_next"))
                                (scale -1.0d0
                                       (product (term 1.0d0 4 :name "m")
                                                (term 1.0d0 1 :name "v")))
                                (scale -1.0d0
                                       (product (term 1.0d0 2 :name "F")
                                                (term 1.0d0 3 :name "dt"))))
                           0 "v_next" "newton-impulse-derived")))))
         (update-chunks (emit-update-chunks problem :chunk-row-count 16))
         (residual-chunks (emit-residual-chunks problem :chunk-row-count 16))
         (source (emit-dispatch-c problem
                                  :residual-chunks residual-chunks
                                  :update-chunks update-chunks)))
    (declare (ignore source))
    ;; The chunk that holds the v_next update must include the inline
    ;; cp_reciprocal helper because the solved expression uses it.
    (let ((reciprocal-chunk
           (find-if (lambda (chunk)
                      (search "cp_reciprocal" (chunk-source-text chunk)))
                    update-chunks)))
      (assert reciprocal-chunk ()
              "expected at least one update chunk to emit cp_reciprocal helper")
      (assert (search "static inline double cp_reciprocal"
                      (chunk-source-text reciprocal-chunk)))))

  ;; Empty residual list still produces a syntactically valid
  ;; compute_residual that does nothing.
  (let* ((problem (make-problem
                   :name "dispatch-empty-residual"
                   :slot-names '("a")
                   :residual-specs (list (cons "trivial"
                                               (term 1.0d0 0 :name "a")))))
         (residual-chunks '())
         (update-chunks (emit-update-chunks problem))
         (source (emit-dispatch-c problem
                                  :residual-chunks residual-chunks
                                  :update-chunks update-chunks)))
    (assert (search "compute_residual(const double *state, double *out_r) {"
                    source))))
