;;; Makefile generation for compose-physics.
;;;
;;; Each problem directory ships a Makefile that compiles every chunk
;;; source plus dispatch.c into position-independent object files and
;;; links them into a single shared library. The toolchain (compiler,
;;; flags, default parallelism) is parameterized so that the Python
;;; CLI can inject what it was invoked with; consumers can rebuild the
;;; library independently of compose-physics by running plain make.
;;;
;;; The Makefile is intentionally small and explicit. It does not use
;;; pattern rules over wildcards; each chunk source is enumerated so
;;; that a partially-corrupted directory fails loudly instead of
;;; silently picking up stray .c files.

(in-package #:compose-physics)


(defparameter *default-c-compiler* "cc"
  "Compiler invoked by the emitted Makefile when CC is not
   overridden on the make command line or in the environment.")


(defparameter *default-c-flags* "-O3 -fPIC -ffast-math -Wall -Wextra"
  "Compilation flags baked into the emitted Makefile when CFLAGS
   is not overridden. -fPIC is mandatory for the shared-library
   link step; the rest are conventional optimization defaults
   suitable for the residual / update kernels this tool emits.")


(defparameter *default-shared-library-extension* "so"
  "Filename extension for the linked shared library. Linux and
   most Unices use 'so'; Darwin would use 'dylib'. The Python CLI
   may override this by passing :library-extension at emission
   time.")


(defun %library-filename (library-stem extension)
  "Return the conventional shared-library filename: lib<STEM>.<EXT>."
  (format nil "lib~A.~A" library-stem extension))


(defun %make-variable-assignment (variable default-value)
  "Render a Makefile assignment that respects an environment-
   provided value: VAR ?= default. With ?=, make uses the value
   from the environment or command line if set, otherwise the
   default. This is what lets `make CC=clang` or `CC=clang make`
   work without editing the file."
  (format nil "~A ?= ~A" variable default-value))


(defun emit-makefile (problem
                      &key
                        residual-chunks
                        update-chunks
                        (library-stem (problem-name problem))
                        (c-compiler *default-c-compiler*)
                        (c-flags *default-c-flags*)
                        (library-extension *default-shared-library-extension*))
  "Return a string containing a complete Makefile that builds the
   shared library from PROBLEM's emitted sources. The Makefile
   enumerates every chunk source plus dispatch.c, compiles each
   to a .o, and links them into lib<LIBRARY-STEM>.<EXT>.

   Toolchain knobs (CC, CFLAGS) are emitted with ?= so they are
   overridable from the environment or the make command line
   without editing the file. Parallelism is the caller's
   responsibility (`make -j N`); the Makefile itself does not
   set a default jobs count."
  (check-type problem problem)
  (check-type library-stem string)
  (check-type c-compiler string)
  (check-type c-flags string)
  (check-type library-extension string)
  (let* ((library-filename (%library-filename library-stem library-extension))
         (chunk-sources (append residual-chunks update-chunks))
         (chunk-source-filenames
          (mapcar #'chunk-source-filename chunk-sources))
         (all-source-filenames
          (append chunk-source-filenames (list "dispatch.c")))
         (all-object-filenames
          (mapcar (lambda (source-filename)
                    (concatenate 'string
                                 (subseq source-filename
                                         0
                                         (- (length source-filename) 2))
                                 ".o"))
                  all-source-filenames)))
    (with-output-to-string (stream)

      (format stream "# Makefile — generated by compose-physics.~%")
      (format stream "# Problem: ~A~%" (problem-name problem))
      (format stream "# Edit at your own risk; this file is regenerated~%")
      (format stream "# every time the problem is re-registered.~%~%")

      (format stream "~A~%"
              (%make-variable-assignment "CC" c-compiler))
      (format stream "~A~%~%"
              (%make-variable-assignment "CFLAGS" c-flags))

      (format stream "LIBRARY := ~A~%~%" library-filename)

      (format stream "SOURCES :=")
      (dolist (source-filename all-source-filenames)
        (format stream " \\~%    ~A" source-filename))
      (format stream "~%~%")

      (format stream "OBJECTS :=")
      (dolist (object-filename all-object-filenames)
        (format stream " \\~%    ~A" object-filename))
      (format stream "~%~%")

      (format stream ".PHONY: all clean~%~%")

      (format stream "all: $(LIBRARY)~%~%")

      (format stream "$(LIBRARY): $(OBJECTS)~%")
      (format stream "~A$(CC) -shared -o $@ $(OBJECTS) -lm~%~%"
              #\Tab)

      (format stream "%.o: %.c~%")
      (format stream "~A$(CC) $(CFLAGS) -c -o $@ $<~%~%"
              #\Tab)

      (format stream "clean:~%")
      (format stream "~Arm -f $(OBJECTS) $(LIBRARY)~%"
              #\Tab))))


(eval-when (:load-toplevel :execute)

  (let* ((problem
          (with-state (x y)
            (make-problem
             :name "makefile-self-check"
             :slot-names (list "x" "y")
             :residual-specs (list (cons "balance" (sum x (scale -1.0d0 y))))
             :update-specs (list (cons "x" (sum x y))))))
         (residual-chunks (emit-residual-chunks problem :chunk-row-count 16))
         (update-chunks (emit-update-chunks problem :chunk-row-count 16))
         (text (emit-makefile problem
                              :residual-chunks residual-chunks
                              :update-chunks update-chunks
                              :library-stem "selfcheck")))
    (assert (search "CC ?= cc" text))
    (assert (search "CFLAGS ?= -O3" text))
    (assert (search "LIBRARY := libselfcheck.so" text))
    (assert (search "residual_chunk_000.c" text))
    (assert (search "update_chunk_000.c" text))
    (assert (search "dispatch.c" text))
    (assert (search "$(CC) -shared -o $@" text))
    (assert (search "$(CC) $(CFLAGS) -c -o $@ $<" text))
    (assert (search ".PHONY: all clean" text)))


  (let* ((problem
          (with-state (a b)
            (make-problem
             :name "makefile-extension-check"
             :slot-names (list "a" "b")
             :residual-specs (list (cons "r" (sum a b)))
             :update-specs nil)))
         (residual-chunks (emit-residual-chunks problem))
         (text (emit-makefile problem
                              :residual-chunks residual-chunks
                              :update-chunks nil
                              :library-stem "alt"
                              :c-compiler "clang"
                              :c-flags "-O0 -g"
                              :library-extension "dylib")))
    (assert (search "CC ?= clang" text))
    (assert (search "CFLAGS ?= -O0 -g" text))
    (assert (search "LIBRARY := libalt.dylib" text)))


  (let* ((tmpdir
          (format nil "/tmp/cp-makefile-selfcheck-~A/" (get-universal-time)))
         (problem
          (with-state (x y)
            (make-problem
             :name "makefile-build-check"
             :slot-names (list "x" "y")
             :residual-specs (list (cons "balance" (sum x (scale -1.0d0 y))))
             :update-specs (list (cons "x" (sum x y))))))
         (residual-chunks (emit-residual-chunks problem))
         (update-chunks (emit-update-chunks problem))
         (dispatch-text
          (emit-dispatch-c problem
                           :residual-chunks residual-chunks
                           :update-chunks update-chunks))
         (makefile-text
          (emit-makefile problem
                         :residual-chunks residual-chunks
                         :update-chunks update-chunks
                         :library-stem "buildcheck")))
    (ensure-directories-exist tmpdir)
    (dolist (chunk (append residual-chunks update-chunks))
      (with-open-file (stream
                       (concatenate 'string
                                    tmpdir
                                    (chunk-source-filename chunk))
                       :direction :output
                       :if-exists :supersede
                       :if-does-not-exist :create)
        (write-string (chunk-source-text chunk) stream)))
    (with-open-file (stream (concatenate 'string tmpdir "dispatch.c")
                            :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create)
      (write-string dispatch-text stream))
    (with-open-file (stream (concatenate 'string tmpdir "Makefile")
                            :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create)
      (write-string makefile-text stream))
    (let* ((process
            (sb-ext:run-program
             "/usr/bin/env"
             (list "make" "-C" tmpdir "-j")
             :output :stream
             :error :stream
             :wait t))
           (exit-status (sb-ext:process-exit-code process)))
      (assert (zerop exit-status) ()
              "make failed in ~A with exit ~D" tmpdir exit-status)
      (assert (probe-file
               (concatenate 'string tmpdir "libbuildcheck.so")) ()
              "expected libbuildcheck.so to be produced in ~A" tmpdir))))
